### ISSUE TITLE
Question number 5 bug

### ISSUE THREAD

**Issue by asolace** [learn-co-curriculum/mutability-quiz#5]
Question number 5.
Certainly the answer is 8, however the quiz says I was wrong and that the answer was 5.
![quiz question 5](https://cloud.githubusercontent.com/assets/22672862/24312936/388a37f6-10b1-11e7-8938-32fac1990719.JPG)

**Comment by morgvanny** [comment]
5 is correct. While the method itself would return 8, it has no ability to actually reassign values of the variables number_one or number_two. So if we run the method, and then check the value of number_one, it will be unchanged. Feel free to test this out in your terminal, using IRB!
